# Generated by Django 5.0.2 on 2024-12-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='feedback_images/')),
            ],
        ),
    ]
